[package]
name = "nemo-physical"
version = "0.1.1-dev"
authors = [
"Stefan Ellmauthaler <stefan.ellmauthaler@tu-dresden.de>",
"Lukas Gerlach <lukas.gerlach@tu-dresden.de>",
"Philipp Hanisch <philipp.hanisch1@tu-dresden.de>",
"Alex Ivliev <alex.ivliev@tu-dresden.de>",
"Markus Krötzsch <markus.kroetzsch@tu-dresden.de>",
"Maximilian Marx <maximilian.marx@tu-dresden.de>"
]	
edition = "2021"

[features]
default = ["timing"]
# Enables time measurements using the "howlong" crate
# If this feature is not enabled, all time measurements will display zero instead
timing = ["dep:howlong"]
no-prefixed-string-dictionary = []

[dependencies]
log = "0.4"
bytesize = "1.2"
thiserror = "1.0"
num = "0.4.0"
ascii_tree = "0.1.1"
once_cell = "1"
linked-hash-map = "0.5.6"
howlong = { version = "0.1", optional = true }

[dev-dependencies]
arbitrary = { version = "1", features = ["derive"] }
rand = "0.8"
env_logger = "*"
test-log = "0.2"
quickcheck = "1"
quickcheck_macros = "1"
