// Declarations
.decl A(A: symbol, B: symbol)
.decl B(A: symbol, B: symbol)
.decl C(A: symbol)
.decl D(A: symbol, B: symbol)
.decl E(A: symbol, B: symbol)
.decl data(A: symbol, B: symbol, C: symbol)

// Facts
data("A", "B", "C").
data("B", "B", "D").
data("A", "E", "F").
data("C", "D", "D").

// Rules
A(X, Z) :- data(X, Y, Z).
B(Y, X) :- A(X, Y).
C(Y) :- B(VariableThatIsNotNeeded, Y).
D(Y, Z) :- data(X, Y, Z).
E(F, E) :- D(E, F).

// Query list
.output A
.output B
.output C
.output D
.output E